{
	"version": 1480711836,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/notasmusicais.png",
		"images/foca-sheet0.png",
		"images/gameover-sheet0.png",
		"images/nota01-sheet0.png",
		"images/nota02-sheet0.png",
		"images/nota03-sheet0.png",
		"images/nota04-sheet0.png",
		"images/sprite-sheet0.png",
		"images/nota05-sheet0.png",
		"images/nota06-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledground.png",
		"images/bglight-sheet0.png",
		"images/plateia-sheet0.png",
		"images/cachorrobanda-sheet0.png",
		"images/cachorrobanda-sheet1.png",
		"images/gatobanda-sheet0.png",
		"images/gatobanda-sheet1.png",
		"images/focabanda-sheet0.png",
		"images/focabanda-sheet1.png",
		"images/telainicial-sheet0.png",
		"images/spriteplay-sheet0.png",
		"images/play-sheet0.png",
		"images/particles.png",
		"media/foca da meia-noite - sweet child o´ mine.ogg",
		"media/som vaias.ogg",
		"media/lisasaxsolobakerstree.ogg",
		"media/aplausos efecto de sonido.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}